### ISSUE TITLE
Type Link State

### ISSUE THREAD

**Issue by drummerjolev** [0916dhkim/typed-react-router#1]
Hey, I came across your [article](https://dev.to/0916dhkim/type-safe-usage-of-react-router-5c44) and started implementing the code into my project. This is such awesome work, thanks so much for putting time into it.

I would like to pass an object into state in `TypedLinkProps`, but I'm very new to TypeScript typings. Right now, i have something like this:
```
<Link to={{ pathname: `${ROUTES.MENU}/${menu.id}`, state: { menu } }} >...</Link>
```

where 'menu' is the object in question. I would like my typed Link to recognize that this `menu` is required in the component that renders this route.

Could you point me in the right direction to add this? Thanks again, keep up the good work.

**Comment by 0916dhkim** [comment]
@drummerjolev First of all, you need to define all your paths like I did in `src/hooks/paths.tsx`. Your `PATHS` can look like this:
```ts
const PATHS = [
  '/',
  '/menu/:id',
] as const;
```
Then you should be able to use your `TypedLink` like this (backtick string templates do not work here because Typescript cannot infer types from those):
```tsx
<TypedLink to='/menu/:id' params={{ id: menu.id }} />
```
Unfortunately, only strings can be passed in as URL parameters. I suggest you use React context for passing JS objects.

**Comment by drummerjolev** [comment]
Thanks @0916dhkim. I ended up using context to pass the object, like you recommended.
